version: '3'

services:
  app:
    image: go-health
    build: .
    environment:
      GO111MODULE: "on"
    ports:
      - 9000:9000
    depends_on:
      - db
      - redis
  redis:
    image: redis:alpine
    restart: always
    volumes:
      - ../data/redis:/data
    healthcheck:
      test: ["CMD", "./redis-healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: health
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      